import Head from 'next/head'
import Image from 'next/image'
import Header from '../components/Header'


export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className='bg-gradient-to-t to-blue-100 via-blue-200 from-blue-500'>
          <Header />
      </header>    
    </div>
  )
}
